version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASS}
      MYSQL_DATABASE: ${DOCKER_DB_NAME}
      MYSQL_USER: ${DOCKER_DB_USER}
      MYSQL_PASSWORD: ${DOCKER_DB_PASS}
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DOCKER_DB_USER}
      PMA_PASSWORD: ${DOCKER_DB_PASS}
    ports:
      - "5000:80"
    depends_on:
      - mysql
