// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Organization struct {
	ID          string
	Name        string
	Description string
	HeaderImg   sql.NullString
	ProfileImg  sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID          string
	Email       string
	Password    sql.NullString
	OauthID     sql.NullString
	Name        string
	Role        string
	Phone       sql.NullString
	Img         sql.NullString
	IsPremium   sql.NullBool
	Lvl         sql.NullInt32
	Dob         sql.NullTime
	Institution sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
