// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
)

type User struct {
	ID       string
	Email    string
	Password sql.NullString
	OauthID  sql.NullString
	Name     string
	Role     string
}
