// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Activity struct {
	ID             string
	OrganizationID string
	Title          sql.NullString
	Note           string
	StartTime      sql.NullTime
	EndTime        sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Category struct {
	ID           string
	CategoryName string
	CreatedAt    sql.NullTime
}

type Event struct {
	ID             string
	OrganizationID string
	Title          string
	Img            sql.NullString
	Description    sql.NullString
	Registrant     sql.NullInt32
	MaxRegistrant  sql.NullInt32
	Date           time.Time
	StartTime      sql.NullTime
	EndTime        sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type EventPricing struct {
	ID        int64
	EventID   string
	EventType sql.NullString
	Price     sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Follower struct {
	ID             int32
	OrganizationID string
	FollowerID     string
	FollowedAt     sql.NullTime
}

type Organization struct {
	ID          string
	Name        string
	Description string
	HeaderImg   sql.NullString
	ProfileImg  sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	UserID      string
}

type Organizer struct {
	ID             string
	OrganizationID sql.NullString
	BankName       sql.NullString
	BankAccount    sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Post struct {
	ID             string
	OrganizationID string
	Content        string
	ImageContent   sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type PostComment struct {
	ID        string
	UserID    string
	PostID    string
	Content   string
	CreatedAt sql.NullTime
}

type PostLike struct {
	ID      int32
	UserID  string
	PostID  string
	LikedAt sql.NullTime
}

type Speaker struct {
	ID          string
	Name        string
	Title       sql.NullString
	Img         sql.NullString
	Description sql.NullString
	EventID     sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID          string
	Email       string
	Password    sql.NullString
	OauthID     sql.NullString
	Name        string
	Role        string
	Phone       sql.NullString
	Img         sql.NullString
	IsPremium   sql.NullBool
	Lvl         sql.NullInt32
	Dob         sql.NullTime
	Institution sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Username    sql.NullString
	Address     sql.NullString
}

type UserCategory struct {
	ID         int32
	CategoryID string
	UserID     string
	CreatedAt  sql.NullTime
}
