// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: organization.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addOrganization = `-- name: AddOrganization :execresult
INSERT INTO organizations (
    id, name, description, header_img, profile_img, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AddOrganizationParams struct {
	ID          string
	Name        string
	Description string
	HeaderImg   sql.NullString
	ProfileImg  sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) AddOrganization(ctx context.Context, arg AddOrganizationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addOrganization,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.HeaderImg,
		arg.ProfileImg,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}
