ALTER TABLE users
    DROP COLUMN phone,
    DROP COLUMN img,
    DROP COLUMN is_premium,
    DROP COLUMN lvl,
    DROP COLUMN dob,
    DROP COLUMN institution,
    DROP COLUMN created_at,
    DROP COLUMN updated_at;