ALTER TABLE users
    ADD COLUMN phone VARCHAR(20),
    ADD COLUMN img VARCHAR(255) NULL AFTER phone,
    ADD COLUMN is_premium BOOLEAN AFTER img,
    ADD COLUMN lvl INT AFTER is_premium,
    ADD COLUMN dob TIMESTAMP AFTER lvl,
    ADD COLUMN institution VARCHAR(255) AFTER dob,
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER institution,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;